### ISSUE TITLE
Weird formatting when loading, no entities identified

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/NERVE#19] opened 2017-09-18 19:09 UTC
TEI schema
file name in screenshot

![image](https://user-images.githubusercontent.com/545952/30559659-5dc301c0-9c83-11e7-973b-3aee44672e11.png)

**Comment by Thaerious** [comment] 2017-10-17 15:42
There are .css formatting issues. I have fixed this particular one but more may crop up.  These can be tweeked fairly easily on the fly.

**Comment by ilovan** [comment] 2017-11-24 21:32
@Thaerious , 

Just tested the same document today. 
It looks like not all the tenties are tagged, and the ones that are tagged are all tagged as place entities. (this may be a different issue altogether - let me know if you want me to put it in a new thread.

![capture](https://user-images.githubusercontent.com/6600070/33224217-47dd9304-d124-11e7-94ae-b0ef14a5d694.PNG)

**Comment by Thaerious** [comment] 2017-11-27 16:40
The missing tags issue has been fixed*, I had missed an async on the load document call.  The incorrectly tagged elements are from the geonames collection and it is the expected behaviour.  The tagging works by first looking for "custom" dictionary entries, then "pre-loaded" dictionary entries such as geonames.  At this point the stanford NER tool will attempt to tag any un-tagged entities.

* I'm going to close this ticket as the tagging issue is mostly resolved.  It has been masked by a delayed call to the layout manager (you'll notice a half second delay after loading a document before the formatter kicks in).  This however is hacky and needs a better fix.  That said, I have yet to find a way to do this, so it's not really a bug.

**Closed by Thaerious** 2017-11-27 16:40 UTC
Labels: bug

**Comment by ilovan** [comment] 2017-11-27 18:22
@Thaerious , would you like these closed closed issues that you know you will need to circle back to eventually labeled as such so that we don't loose track of the documentation and troubleshooting included with them?

**Comment by Thaerious** [comment] 2017-11-27 18:28
This ticket probably should have been 3 different tickets: CSS, mis-tagging, and untagged entities.  The css is still in progress, and can be fixed by anyone, it's a time issue.  I think that one can remain a ticket.  The mis-tagging isn't a bug, it's a matter of the dictionaries not being very populated yet.  The untagged entities are a matter of how they are displayed, it's a technology answer that I don't know the answer to yet.  But in short I would close this ticket, and maybe open a new css ticket.

**Comment by susanirenebrown** [comment] 2017-11-27 22:09
What is involved in populating the dictionaries more fully?I take it we are not talking whitelists but what lookups (e.g. VIAF) are involved?

**Comment by Thaerious** [comment] 2017-11-29 13:58
Whitelists are dictionaries, previously tagged and saved entities that will be tagged in future documents.  To populate the dictionaries all that is required are records entered into the mysql database. 

Each record consist of: entity text (which matches the text in a document), lemma (common name), link, tag, & collection.
